base:
  random_state: 42
  test_size: 0.2

model_params:
  naive_bayes:
    var_smothing:
      [ 1e-9, 0.1, 0.001, 0.5, 0.05, .01, 1e-8, 1e-7, 1e-6, 1e-10, 1e-11 ]
    cv: 3
    verbose: 3
  random_forest:
    n_estimators: [ 5,10,50,100,120,150 ],
    criterion: [ "mse", "mae" ],
    max_depth: range(10),
    min_samples_leaf: range(10)