data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv

  model_dir: model_dir
  model_filename: random_forest.model

  reports_dir: reposrts_dir
  scores: scores.json